services:
  # Backend API (Laravel)
  - type: web
    name: nutsshop-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/health
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: nutsshop-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: nutsshop-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: nutsshop-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: nutsshop-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: nutsshop-db
          property: password
      - key: APP_URL
        value: https://nutsshop-api.onrender.com
      - key: FRONTEND_URL
        value: https://nutsshop-frontend.onrender.com
      - key: APP_KEY
        value: "base64:wUWpDUjMCeVt47X24ylKV57JRNkKCR52kwogyoqTxFQ="
      - key: PORT
        value: 8080

  # Frontend (Nuxt.js)
  - type: web
    name: nutsshop-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: NODE_ENV
        value: production
      - key: NUXT_PUBLIC_API_BASE_URL
        value: https://nutsshop-api.onrender.com
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 3000
      - key: NUXT_SKIP_TS_CHECK
        value: "true"

# PostgreSQL database
databases:
  - name: nutsshop-db
    plan: basic-1gb
    ipAllowList: [] 